raw_files_location: /usr/local/etc/raw_files
log_file_location: /var/log/intelcollector/intelcollector.log
validated_files_location: /usr/local/etc
update_every:
  minutes: 1
intel_list: /usr/local/etc/intel_list.yaml
